---
- hosts: webserver
  remote_user: test
  become: yes
  tasks: 
     - name: install packages
       yum: name={{item}} state=installed
       with_items:
           - httpd
           - curl
           - telnet
